Warn if ASA is used in combination with events
AMICI-dev/AMICI pull request #2097
Opened 2023-05-17 16:33 UTC by dweindl

#18

2023-05-18 06:51 UTC, FFroehlich reviewed
‚ne‘ counts discontinuities in the rhs and x. Discontinuities in the rhs are fine with adjoint sensitivity analysis as long as the trigger function is not parameter dependent.

2023-05-22 06:47 UTC, dweindl commented
> ‚ne‘ counts discontinuities in the rhs and x. Discontinuities in the rhs are fine with adjoint sensitivity analysis as long as the trigger function is not parameter dependent.

Ok, thanks. As this is not apparent from the generated model module, and i don't feel like storing it there - how do we want to handle that?

1) change the message and live with the warnings for non-parameter-dependent trigger functions
2) rather warn once during model import 
3) leave it as it was

2023-05-22 10:07 UTC, FFroehlich commented
> > ‚ne‘ counts discontinuities in the rhs and x. Discontinuities in the rhs are fine with adjoint sensitivity analysis as long as the trigger function is not parameter dependent.
> 
> Ok, thanks. As this is not apparent from the generated model module, and i don't feel like storing it there - how do we want to handle that?
> 
> 1. change the message and live with the warnings for non-parameter-dependent trigger functions
> 2. rather warn once during model import
> 3. leave it as it was before (no warning)

Hmm rephrase and state that it might not apply to the model at hand?

2023-05-26 09:17 UTC, FFroehlich requested changes

2023-05-26 09:17 UTC, FFroehlich commented on python/sdist/amici/swig_wrappers.py
> +            "If your model does not have parameter-dependent trigger functions, you can safely ignore this message."
```suggestion
            "Adjoint sensitivity analysis may work if the location of the discontinuity is not parameter-dependent, but we still recommend testing accuracy of gradients."
```

2023-05-26 09:17 UTC, FFroehlich commented on python/sdist/amici/swig_wrappers.py
> +            "Adjoint sensitivity analysis for models with events with parameter-dependent trigger functions has not been thoroughly tested. "
```suggestion
            "Adjoint sensitivity analysis for models with discontinuous right hand sides (events/piecewise functions) has not been thoroughly tested. "
```

2023-05-26 09:17 UTC, FFroehlich commented on python/sdist/amici/swig_wrappers.py
> +            "If your model does not have parameter-dependent trigger functions, you can safely ignore this message."
```suggestion
            "Adjoint sensitivity analysis may work if the location of the discontinuity is not parameter-dependent, but we still recommend testing accuracy of gradients."
```

2023-05-26 10:43 UTC, FFroehlich approved these changes

2023-05-26 10:47 UTC, merged